# spss表示siyuan-publig-share-system

services:
  # 服务名,不可更改
  spss_nginx:

    # 镜像名,不建议修改
    image: "nginx:1.25.4"
    # 容器名,不建议修改，启停时所需要的参数
    container_name: spss_nginx

    # 端口映射，宿主端口将作为分享链接的中的地址端口，如果是80和443，输出的分享地址将忽略此端口
    # 支持格式：宿主端口:容器端口，0.0.0.0:宿主端口:容器端口
    # 目前仅支持第第一条映射参数，暂不支持更多的端口映射
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # html的资源文件夹，spsse_engine的资源文件将保存与此
      # html的映射路径需要和nginx.conf的root指令相吻合
      - ./nginx/html:/etc/nginx/html
      # 存放ssl证书的文件夹
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - /etc/localtime:/etc/localtime
    # 停止时，是否重启，不建议修改
    restart: always
    # 网络配置，不可删除
    networks:
      - spss_network

  spss_mysql:
    # 镜像名,不建议修改
    image: "mysql:5.7.43"

    # 容器名,不建议修改，启停时所需要的参数
    container_name: spss_mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'share_system'
      MYSQL_PASS: 'password'
      MYSQL_DATABASE: 'share_system'
    restart: always
    privileged: true

    # 网络配置，不可删除
    networks:
      - spss_network

  spss_engine:
    # 构建的镜像名和tag，不建议修改
    image: "spss_engine:1.3.1"

    # 容器名,不建议修改，启停时所需要的参数
    container_name: spss_engine

    # 构建容器，不可修改
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      
    # 容器内的变量
    environment:
      # 不可修改
      SPSS_STARTUP_ENV: "docker"

      # 分享链接的基本地址，可以修改，
      # 如果容器已经启动，但需要修改此变量，可以先修改docker-compose.yml，再执行
      # docker-compose restart spss_engine
      # 对于https的格式，示例: https://example.com
      # 如果你希望分享地址带上端口，那么同时修改nginx容器映射的主机端口
      # v1.1.1及以前的SHARE_BASE_LINK和nginx映射的主机端口共同组成分享地址
      # v1.2.0及之后的SHARE_BASE_LINK作为完整的分享地址，SHARE_BASE_LINK的端口要与nginx容器映射的宿主端口一致，80和443可以忽略
      SHARE_BASE_LINK: "http://127.0.0.1"

      # 不建议修改，如果要修改，同时修改spss_engine的映射地址
      SAVE_PATH: "/data"

      # 不建议修改，如果要修改，同时修改docker/nginx/nginx.conf里的对应的端口
      LISTEN_PORT: 25934

      # 不建议修改，本程序所使用的HTTP框架
      GIN_MODE: release

    # 意外停止时的重启动作，不建议修改
    restart: always
    # 挂载的文件夹，不建议修改
    volumes:
      - ./:/data
      - /etc/localtime:/etc/localtime
    # 网络配置，不可删除
    networks:
      - spss_network
# 网络配置，不可删除
networks:
  spss_network: