# spss表示siyuan-publig-share-system

services:
  # 服务名,不可更改
  spss_nginx:

    # 镜像名,不建议修改
    image: "nginx:1.25.4"
    # 容器名,不建议修改，启停时所需要的参数
    container_name: spss_nginx

    # 端口映射，本地端口:容器端口，本地端口将作为分享链接的中的地址端口，如果是80，分享地址将忽略
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # html的资源文件夹，spsse_engine的资源文件将保存与此
      # html的映射路径需要和nginx.conf的root指令相吻合
      - ./nginx/html:/etc/nginx/html
      - ./nginx/logs:/var/log/nginx

    # 停止时，是否重启，不建议修改
    restart: always
    # 网络配置，不可删除
    networks:
      - spss_network

  spss_mysql:
    # 镜像名,不建议修改
    image: "mysql:5.7.43"

    # 容器名,不建议修改，启停时所需要的参数
    container_name: spss_mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'share_system'
      MYSQL_PASS: 'password'
      MYSQL_DATABASE: 'share_system'
    restart: always
    privileged: true

    # 网络配置，不可删除
    networks:
      - spss_network

  spss_engine:
    # 构建的镜像名和tag，不建议修改
    image: "spss_engine:1.1.0"

    # 容器名,不建议修改，启停时所需要的参数
    container_name: spss_engine

    # 构建容器，不可修改
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      
    # 容器内的变量
    environment:
      # 不可修改
      SPSS_STARTUP_ENV: "docker"

      # 分享链接的基本地址，可以修改，
      # 此参数结合nginx的映射的本地端口，组成完整的分享地址，
      # 如果容器已经启动，但需要修改此变量，可以先修改docker-compose.yaml，再执行
      # docker-compose restart spss_engine
      SHARE_BASE_LINK: "http://127.0.0.1"
      # 不建议修改，如果要修改，同时修改spss_engine的映射地址
      SAVE_PATH: "/data"
      # 不建议修改，如果要修改，同时修改nginx.conf里的对应的端口
      LISTEN_PORT: 25934
      # 不建议修改，本程序适用的HTTP框架
      GIN_MODE: release
    # 意外停止时的重启动作，不建议修改
    restart: always
    # 挂载的文件夹，不建议修改
    volumes:
      - ./:/data
    # 网络配置，不可删除
    networks:
      - spss_network
# 网络配置，不可删除
networks:
  spss_network: