version: '3.7'
services:
  nginx:
    image: "nginx:1.25.4"
    container_name: spss_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    restart: always

  db:
    image: "mysql:5.7.43"
    container_name: spss_mysql
    volumes:
      - "./data:/var/lib/mysql"
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'share_system'
      MYSQL_PASS: 'password'
    restart: always
    privileged: true

  app:
    container_name: spss_engine
    build:
      context: ../
      dockerfile: ./docker/Dockerfile